version: "3"
services:
   linked_data_server:
      image: ghcr.io/zazuko/trifid
      ports:
         - "8174:8080"
      environment:
         SPARQL_ENDPOINT_URL: "http://sparql_endpoint:9999/blazegraph/namespace/kb/sparql"
         #OJO, antes estaba activo el um.es. Lo he cambiado por el dayhoff, que contiene el nombre de mi ontologia
         #DATASET_BASE_URL: "https://um.es/data/"
         #DATASET_BASE_URL: "http://dayhoff.inf.um.es/ontologies/"
         DATASET_BASE_URL: "http://dayhoff.inf.um.es/ontologies/GlycogenStorageDisease#"
         #DATASET_BASE_URL: "http://fair/data/"


   sparql_endpoint:
      image: blazegraph
      ports:
         - "3034:9999"



         
